version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/hello-world-app/build

hooks:
  BeforeInstall:
    - location: cleanoldfile.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: installdepen.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: servicestart.sh
      timeout: 300
      runas: root
