version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/hello-world-app/build

hooks:
  BeforeInstall:
    - location: scripts/clean_old_files.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: root
