version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/hello-world-app/build

hooks:
  BeforeInstall:
    - location: scripts/cleanoldfile.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/installdepen.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/servicestart.sh
      timeout: 300
      runas: root
